name: PlayerTitles
version: '${project.version}'
main: nuclearkat.playertitles.PlayerTitlesPlugin
api-version: '1.20'
commands:
  titles:

  createTitle:

  disableTitle:

  savetitles:

depend:
  - [PlaceholderAPI]